name: one_more_idea
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.2.0+1
  flutter_staggered_grid_view: ^0.3.0
  flutter_swiper: ^1.1.6
  provider: ^2.0.0
  http: ^0.12.2
  html: ^0.14.0+3
  url_launcher: ^5.5.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
 

flutter:

  uses-material-design: true

